name: CI-Lint-And-Test

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - davidsebek/wasm-experiments

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  BLITZAR_BACKEND: cpu

jobs:
  # Run cargo check (with various feature permutations)
  check:
    name: Check Package
    runs-on: large-8-core-32gb-22-04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.toml') }}
      - name: Install stable toolchain
        run: curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal && source ~/.cargo/env
      - name: Install Dependencies
        run: export DEBIAN_FRONTEND=non-interactive && sudo apt-get update && sudo apt-get install -y clang lld     
      - name: Run cargo check (no features, exclude examples)
        run: cargo check --no-default-features
      - name: Run cargo check (default features)
        run: cargo check --all-targets
      - name: Run cargo check (all features)
        run: cargo check --all-targets --all-features
      - name: Run cargo check (proof-of-sql) (no features)
        run: cargo check -p proof-of-sql --no-default-features
      - name: Run cargo check (proof-of-sql) (all features)
        run: cargo check -p proof-of-sql --all-features
      - name: Run cargo check (proof-of-sql) (just "test" feature)
        run: cargo check -p proof-of-sql --no-default-features --features="test"
      - name: Run cargo check (proof-of-sql) (just "blitzar" feature)
        run: cargo check -p proof-of-sql --no-default-features --features="blitzar"

  test:
    name: Test Suite
    runs-on: large-8-core-32gb-22-04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}
      - name: Install stable toolchain
        run: curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal && source ~/.cargo/env
      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=non-interactive
          sudo apt-get update
          sudo apt-get install -y clang lld
      - name: Run cargo test
        run: cargo test --all-features
      - name: Dry run cargo test (proof-of-sql) (test feature only)
        run: cargo test -p proof-of-sql --no-run --no-default-features --features="test"
      - name: Dry run cargo test (proof-of-sql) (arrow feature only)
        run: cargo test -p proof-of-sql --no-run --no-default-features --features="arrow"
      - name: Dry run cargo test (proof-of-sql) (blitzar feature only)
        run: cargo test -p proof-of-sql --no-run --no-default-features --features="blitzar"
      - name: Dry run cargo test (proof-of-sql) (no features)
        run: cargo test -p proof-of-sql --no-run --no-default-features
      - name: Run cargo test (proof primitives - Dory) (no features - i.e. not using blitzar)
        run: cargo test proof_primitive::dory::dory_compute_commitments_test --no-default-features
      - name: Run hello_world example
        run: cargo run --example hello_world --features="blitzar test"
      - name: Run posql_db example
        run: bash crates/proof-of-sql/examples/posql_db/run_example.sh

  test-wasm:
    name: Test Wasm
    runs-on: large-8-core-32gb-22-04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-wasm-${{ hashFiles('**/Cargo.toml') }}
      - name: Install stable toolchain
        run: curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal && source ~/.cargo/env
      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=non-interactive
          sudo apt-get update
          sudo apt-get install -y clang lld
      - name: Add Wasm toolchain
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install --force wasm-pack
      - name: Install Deno
        run: curl -fsSL https://deno.land/install.sh | sh
      - name: Build a Wasm
        run: |
          CARGO_PROFILE_RELEASE_OPT_LEVEL=z wasm-pack build --release --target deno --no-typescript --no-pack ./crates/verifier-wasm
          rm -rf ./verifier-wasm-artifacts
          mv ./crates/verifier-wasm/pkg ./verifier-wasm-artifacts
      - name: Generate test inputs
        run: |
          cargo run -p verifier-wasm-tester -- ./verifier-wasm-inputs
      - name: Run Wasm with Deno
        run: |
          export DENO_INSTALL="$HOME/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno run --allow-read crates/verifier-wasm-tester/js/run_verifier_wasm.js ./verifier-wasm-inputs | tail -1 | grep 'Verification SUCCESS'

  clippy:
    name: Clippy
    runs-on: large-8-core-32gb-22-04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.toml') }}
      - name: Install stable toolchain
        run: |
          curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal && source ~/.cargo/env
          rustup component add clippy
      - name: Install Dependencies
        run: export DEBIAN_FRONTEND=non-interactive && sudo apt-get update && sudo apt-get install -y clang lld
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  # Run cargo fmt --all -- --config imports_granularity=Crate,group_imports=One --check
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        run: |
          curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal && source ~/.cargo/env
          rustup component add rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --config imports_granularity=Crate,group_imports=One --check

  udeps:
    name: Unused Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nightly toolchain
        run: |
          curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal && source ~/.cargo/env && rustup default nightly
          cargo install cargo-udeps --locked
      - name: Run cargo udeps
        run: cargo +nightly udeps --all-targets

  foundrycheck: # Modified from the foundry book: https://book.getfoundry.sh/config/continuous-integration
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run tests
        run: forge test --root=crates/proof-of-sql --summary --detailed

  solhint:
    name: solhint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install solhint
        run: npm install -g solhint
      - name: Run tests
        run: solhint -c 'crates/proof-of-sql/.solhint.json' 'crates/proof-of-sql/**/*.sol' -w 0
